# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20170310_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='length_minutes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='length_seconds',
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.TimeField(blank=True, null=True, verbose_name='song length'),
        ),
    ]
