# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_auto_20170313_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='albums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band_albums', to='bands.Album', verbose_name='albums'),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band_genre', to='bands.Genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), verbose_name='image'),
        ),
    ]
