# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_auto_20170323_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('title'), verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_song', to='bands.Song', verbose_name='songs'),
        ),
    ]
