# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_auto_20170323_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='bands.Song', verbose_name='songs'),
        ),
        migrations.AlterField(
            model_name='band',
            name='albums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band', to='bands.Album', verbose_name='albums'),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bands_in_genre', to='bands.Genre', verbose_name='genre'),
        ),
    ]
