# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
        ('auth_ex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(null=True, upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('username'), verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='followed_bands',
            field=models.ManyToManyField(blank=True, related_name='followed_bands', to='bands.Band', verbose_name='Bands'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_band_manager',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a band manager and therefore can realize band actions.', verbose_name='band manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_band',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_band', to='bands.Band'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', error_messages={'unique': 'A user with that username already exists.'}, max_length=30, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
