# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0002_auto_20170310_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_bands',
            field=models.ManyToManyField(blank=True, related_name='followers', to='bands.Band', verbose_name='Bands'),
        ),
        migrations.AlterField(
            model_name='user',
            name='managed_band',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='bands.Band'),
        ),
    ]
